title: Pallapu Mohan Krishna
logo: /assets/images/pmk_photo.png
description: Pursuing PhD at Mehta Family School Of Data Science and Artificial Intelligence
#show_downloads: true
theme: jekyll-theme-minimal
