title: Pallapu Mohan Krishna
logo: /assets/images/pmk_photo.png
description: Pursuing PhD at Mehta Family School Of Data Science and Artificial Intelligence
Linkedin : https://www.linkedin.com/in/mohan-krishna-pallapu/
#show_downloads: true
theme: jekyll-theme-alfolio
